n1 = input('Digite o nome do cliente: ')
n2 = input('Digite a data de vencimento: ')
n3 = input('Digite o mês de vencimento: ')
n4 = input('Digite o valor da fatura: ')
print('Olá {}.'.format(n1))
print('A sua fatura com vencimento em {} de {} no valor de R${}'.format(n2,n3,n4))
print('está fechada.')